//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GridShadingPuzzle.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int GridSize {
            get {
                return ((int)(this["GridSize"]));
            }
            set {
                this["GridSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3,3;3,4;3,12;3,13;3,21;8,6;8,7;8,10;8,14;8,15;8,18;16,6;16,11;16,16;16,20;21,3;21" +
            ",4;21,9;21,10;21,15;21,20;21,21")]
        public string InitialBlackCells {
            get {
                return ((string)(this["InitialBlackCells"]));
            }
            set {
                this["InitialBlackCells"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"7,3,1,1,7;1,1,2,2,1,1;1,3,1,3,1,1,3,1;1,3,1,1,6,1,3,1;1,3,1,5,2,1,3,1;1,1,2,1,1;7,1,1,1,1,1,7;3,3;1,2,3,1,1,3,1,1,2;1,1,3,2,1,1;4,1,4,2,1,2;1,1,1,1,1,4,1,3;2,1,1,1,2,5;3,2,2,6,3,1;1,9,1,1,2,1;2,1,2,2,3,1;3,1,1,1,1,5,1;1,2,2,5;7,1,2,1,1,1,3;1,1,2,1,2,2,1;1,3,1,4,5,1;1,3,1,3,10,2;1,3,1,1,6,6;1,1,2,1,1,2;7,2,1,2,5")]
        public string Rows {
            get {
                return ((string)(this["Rows"]));
            }
            set {
                this["Rows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"7,2,1,1,7;1,1,2,2,1,1;1,3,1,3,1,3,1,3,1;1,3,1,1,5,1,3,1;1,3,1,1,4,1,3,1;1,1,1,2,1,1;7,1,1,1,1,1,7;1,1,3;2,1,2,1,8,2,1;2,2,1,2,1,1,1,2;1,7,3,2,1;1,2,3,1,1,1,1,1;4,1,1,2,6;3,3,1,1,1,3,1;1,2,5,2,2;2,2,1,1,1,1,1,2,1;1,3,3,2,1,8,1;6,2,1;7,1,4,1,1,3;1,1,1,1,4;1,3,1,3,7,1;1,3,1,1,1,2,1,1,4;1,3,1,4,3,3;1,1,2,2,2,6,1;7,1,3,2,1,1")]
        public string Columns {
            get {
                return ((string)(this["Columns"]));
            }
            set {
                this["Columns"] = value;
            }
        }
    }
}
